Avoid adding VM bootclasspath when possible
SonarSource/sonar-java pull request #3229
Opened 2020-10-01 12:11 UTC by henryju

SonarLint Eclipse and IntelliJ are passing the right android.jar/rt.jar/jrt-fs.jar as part of `sonar.java.libraries`, so in this case it is better to not prepend to VM bootclasspath to avoid FP/FN.

2020-10-01 15:03 UTC, m-g-sonar requested changes

2020-10-01 15:03 UTC, m-g-sonar commented on its/plugin/tests/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
unrequired change.

2020-10-01 15:03 UTC, m-g-sonar commented on its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaClasspathTest.java
> +        " please use sonar.java.binaries and sonar.java.libraries instead");
unrequired change

2020-10-02 13:53 UTC, henryju commented on java-frontend/src/test/java/org/sonar/java/model/JParserTest.java
> +  private VariableTree parseAndGetVariable(String code, File... classpath) {
This allows to provide no arguments as well

2020-10-08 06:32 UTC, merged