Fix FP S1170 for final fields having lombok.Builder.Default
SonarSource/sonar-java pull request #3258
Opened 2020-11-06 16:53 UTC by steven-sheehy

Please ensure your pull request adheres to the following guidelines: 

- [x] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [x] Unit tests are passing and you provided a unit test for your fix
- [ ] ITs should pass : To run ITs locally, checkout the [README](https://github.com/SonarSource/sonar-java/blob/master/README.md) of the project.
- [ ] If there is a [Jira](http://jira.sonarsource.com/browse/SONARJAVA) ticket available, please make your commits and pull request start with the ticket number (SONARJAVA-XXXX)

2020-11-12 17:18 UTC, quentin-jaquier-sonarsource requested changes
Hello @steven-sheehy ,

Thank you very much for taking the time to contribute.
> If there is a Jira ticket available [...]

A ticket describing this problem already exits: [SONARJAVA-3579](https://jira.sonarsource.com/browse/SONARJAVA-3579)

Otherwise, the logic behind the fix you implemented looks good, I just have a few comments concerning the tests, I let you have a look.

2020-11-12 20:29 UTC, steven-sheehy commented on java-checks/src/test/files/filters/LombokFilter.java
> +    private final int bar = 1; // WithIssue
Test case added

2020-11-12 20:29 UTC, steven-sheehy commented on java-checks/src/main/java/org/sonar/java/filters/LombokFilter.java
> +  private static final String LOMBOK_BUILDER = "lombok.Builder";
I changed it to reuse the constant.

2020-11-12 20:29 UTC, steven-sheehy commented on java-checks/src/test/files/filters/LombokFilter.java
> +    private final int bar = 1; // NoIssue
Sure, I separated out the tests, added some comments and made the fields public.

2020-11-13 09:30 UTC, quentin-jaquier-sonarsource approved these changes

2020-11-13 09:33 UTC, quentin-jaquier-sonarsource commented
I duplicated your PR (see #3265) in order to trigger the QA: everything is green, well done!

Your fix will be part of our next release to be included in SonarQube 8.6, and available on SonarCloud a few days after.

Thank you.

2020-11-13 09:33 UTC, closed without merging