SONARJAVA-3632 Rule S6104: Map "computeIfAbsent()" should not be used to add "null" values.
SonarSource/sonar-java pull request #3346
Opened 2020-12-10 16:00 UTC by dorian-burihabwa-sonarsource

2020-12-11 09:53 UTC, quentin-jaquier-sonarsource requested changes
In addition, I think you could have squashed some of the commits of your branch. It makes sense to separate some of them to keep a history of what you tried, help the reviewer or intent to keep all the commit separated in master.

2020-12-11 09:53 UTC, quentin-jaquier-sonarsource commented on java-checks/src/test/java/org/sonar/java/checks/NullReturnedOnComputeIfPresentOrAbsentCheckTest.java
> +      .newVerifier()
Same here idea as the comment in the main code, you don't need to separate the method call from the type.

2020-12-11 09:53 UTC, quentin-jaquier-sonarsource commented on java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S6104_java.html
> +<p> * {rule:squid:S3824} - "Map.get" and value test should be replaced with single method call</p>
This is a bug in `ruleapi`, this should be an HTML list. 
This is due to the fact that a space is sometimes inserted automatically before the `*` in the [rspec](https://jira.sonarsource.com/browse/RSPEC-6104). I updated the description to fix it, you can re-generate the description.

2020-12-11 16:08 UTC, dorian-burihabwa-sonarsource commented
If the code changes are satisfactory enough, I can squash and rebase on master

2020-12-14 15:35 UTC, quentin-jaquier-sonarsource reviewed
A last small formatting comment, otherwise, LGTM!

2020-12-14 15:35 UTC, quentin-jaquier-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/NullReturnedOnComputeIfPresentOrAbsentCheck.java
> +  @Override
This annotation should go after the javadoc.

2020-12-14 16:36 UTC, quentin-jaquier-sonarsource approved these changes
LGTM, well done!

2020-12-14 16:36 UTC, merged