SONARJAVA-3769: Remove record fields from reporting in S3011(Reflection fields update)
SonarSource/sonar-java pull request #3671
Opened 2021-06-29 12:59 UTC by dorian-burihabwa-sonarsource

2021-06-30 13:22 UTC, sebastian-hungerecker-sonarsource requested changes
This looks good to me. I've made some suggestions for improvements and, as discussed, I won't merge until after the companion rule has been implemented because the excluded cases are still useful until the other rule is implemented to cover them.

You should also add test cases to bring up the coverage.

2021-06-30 13:44 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/AccessibilityChangeCheck.java
> +    if (isJava16OrGreater && isModifyingFieldFromRecord(mit)) {
That sounds fair, the version check will be removed.

Please note that It looks like the Java version chosen in our tests does not enable the preview features. For instance, the [local type inference with var](https://github.com/SonarSource/sonar-java/blob/a1be09304b53d67f6c45182a9f4f83302fa58e80/java-checks/src/test/java/org/sonar/java/checks/VarCanBeUsedCheckTest.java#L37) needs to set the version to 10 for the `var` keyword to be properly processed.

2021-06-30 13:47 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/AccessibilityChangeCheck.java
> +    MemberSelectExpressionTree memberSelect = (MemberSelectExpressionTree) fieldModificationExpression;
Will fix that

2021-07-06 08:41 UTC, dorian-burihabwa-sonarsource commented
These changes have been made part of SONARJAVA-3768 (#3673).

2021-07-06 08:41 UTC, closed without merging