SONARJAVA-3952 Add quick fix for BigDecimal with two arguments
SonarSource/sonar-java pull request #3748
Opened 2021-08-18 16:08 UTC by quentin-jaquier-sonarsource

2021-08-19 08:58 UTC, alban-auzeill requested changes

2021-08-19 08:58 UTC, alban-auzeill commented on java-checks-test-sources/src/main/java/checks/BigDecimalDoubleConstructorCheck.java
> +  // fix@qf1_2 {{Replace with BigDecimal("2.0")}}
The replacement message is misleading, it shows a missing `MathContext` argument.
And without the MathContext, the value is not the same, for example:
```
    MathContext mathContext = new MathContext(3, RoundingMode.FLOOR);
    System.out.println(new BigDecimal(1.2345f, mathContext)); // => 1.23
    System.out.println(new BigDecimal("1.2345")); // => 1.2345
```
We could perhaps say `Replace with BigDecimal("2.0",`

2021-08-19 08:58 UTC, alban-auzeill commented on java-checks/src/main/java/org/sonar/java/checks/BigDecimalDoubleConstructorCheck.java
> +    if (argumentValue.endsWith("f") || argumentValue.endsWith("d")) {
Warning, the decimal suffix is case insensitive: `1.0f` == `1.0F` and `1.0d` == `1.0D`

2021-08-19 15:28 UTC, quentin-jaquier-sonarsource commented
I took the opportunity to also fix the message, suggesting to use `valueOf` even when there is a MathContext. We should suggest using the String constructor instead.

2021-08-23 07:01 UTC, alban-auzeill approved these changes

2021-08-23 07:02 UTC, merged