SONARJAVA-3917 Add quick fixes for S1161 (OverrideAnnotationCheck)
SonarSource/sonar-java pull request #3749
Opened 2021-08-19 10:08 UTC by m-g-sonar

2021-08-20 08:54 UTC, quentin-jaquier-sonarsource requested changes

2021-08-20 08:54 UTC, quentin-jaquier-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/OverrideAnnotationCheck.java
> +    return newLineSequence;
In practice
```
  static class InnerClassSingleLine extends OverrideAnnotationCheckSimple { public void get() { } }
```
becomes (in my IDE)
```
  static class InnerClassSingleLine extends OverrideAnnotationCheckSimple {
    @Override
  public void get() { } }
```



If the method contains something before at the same line, we are already talking about strange formatted code, I don't think we should try to do something smart to cleanly add the code, a simple space (even without a new line) seems enough.

2021-08-20 08:54 UTC, quentin-jaquier-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/OverrideAnnotationCheck.java
> +    for (int i = firstLine.length() - 1; i == 0; i--) {
You have a problem with the condition of this loop!

2021-08-20 12:28 UTC, m-g-sonar commented on java-checks-test-sources/src/main/java/checks/OverrideAnnotationCheck_QuickFixes.java
> +
I actually need these parts to create the condition for the quick-fixes

2021-08-20 20:29 UTC, m-g-sonar commented on java-checks-test-sources/src/main/java/checks/OverrideAnnotationCheck_QuickFixes.java
> +
but indeed i can simplify a bit

2021-08-23 07:29 UTC, quentin-jaquier-sonarsource approved these changes
LGTM

2021-08-23 07:29 UTC, merged