SONARJAVA-4199 Document new properties
SonarSource/sonar-java pull request #4007
Opened 2022-03-22 15:01 UTC by quentin-jaquier-sonarsource

2022-03-22 15:03 UTC, alban-auzeill approved these changes

2022-03-22 15:23 UTC, agigleux requested changes

2022-03-22 15:23 UTC, agigleux commented on sonar-java-plugin/src/main/resources/static/documentation.md
> +It is possible to manually set this value by using the property `sonar.java.experimental.batchModeSizeInKB`.
Now that Batch Mode is the default, I don't think we should keep the word "experimental" in the name of the property.

2022-03-22 15:23 UTC, agigleux commented on sonar-java-plugin/src/main/resources/static/documentation.md
> +More details can be found in the [wiki of the analyzer](https://github.com/SonarSource/sonar-java/wiki/Batch-mode).
Personally, I won't use the wording "wiki of the analyzer".
Instead just use: 

`More details can be found [here](https://github.com/SonarSource/sonar-java/wiki/Batch-mode)`

2022-03-24 09:47 UTC, agigleux approved these changes

2022-03-24 09:50 UTC, merged