Vert.x methods for JUnit5 in AssertionsInTestsCheck
SonarSource/sonar-java pull request #4141
Opened 2022-07-04 17:14 UTC by julianladisch

Add these methods of Eclipse Vert.x with JUnit 5 (VertxTestContext)
to list of assertion methods:
* laxCheckpoint
* succeedingThenComplete

Exclude these methods of Eclipse Vert.x with JUnit 5 (VertxTestContext)
from list of assertion methods:
* verify
* failing

Upgrade Vert.x version from 3.5.4 to 4.3.1. This requires code changes
in VertxJUnit4.java because HttpClient changed in Vert.x 4.

Use vertx-stack-depchain dependencyManagement, this also
manages netty-all, jackson-annotations, jackson-databind.

2023-02-09 10:47 UTC, johann-beleites-sonarsource commented
Tracked in [SONARJAVA-4413](https://sonarsource.atlassian.net/browse/SONARJAVA-4413)

[SONARJAVA-4413]: https://sonarsource.atlassian.net/browse/SONARJAVA-4413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-01-16 13:08 UTC, ADarko22 commented
@julianladisch, thanks for your PR; it looks nice! Could you please rebase it on `master` and resolve the conflicts? Most conflicts come from splitting the **java-checks-test-sources** module into submodules: you may need to add the required dependencies in the **java-checks-test-sources/default** submodule.

Once you solve those conflicts, I will merge your changes.

2024-01-16 13:16 UTC, ADarko22 requested changes
Please resolve the conflicts, then we will review the changes that overall look very nice!

2024-01-16 15:43 UTC, ADarko22 commented on java-checks/src/main/java/org/sonar/java/checks/helpers/UnitTestUtils.java
> +      "|laxCheckpoint|succeedingThenComplete" // Eclipse Vert.x with JUnit 5 (VertxTestContext)
please move the comment on the line above

2024-01-19 08:34 UTC, ADarko22 requested changes

2024-01-19 08:35 UTC, ADarko22 commented
> @ADarko22 I've rebased the PR.

@julianladisch thank you! I left two small comments, please have a look then everything should be ready for merge :)

2024-01-19 13:44 UTC, closed without merging