SONARJAVA-4464 Restrict the use of the sonar.java.enablePreview flag to the greatest supported Java version
SonarSource/sonar-java pull request #4367
Opened 2023-04-28 13:54 UTC by dorian-burihabwa-sonarsource

2023-04-28 15:02 UTC, dorian-burihabwa-sonarsource commented
This change comes as a result of the feedback on  #4364 (see [latest comments](https://github.com/SonarSource/sonar-java/pull/4364#pullrequestreview-1404433208)) and prevents users and developers from setting `sonar.java.enablePreview` flag to `true` when the java version number is lower than the maximum supported version

2023-04-28 15:40 UTC, alban-auzeill requested changes

2023-04-28 15:40 UTC, alban-auzeill commented on sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaSensor.java
>    private JavaVersion getJavaVersion() {
When `settings.get(JavaVersion.ENABLE_PREVIEW)` is empty we should return `new JavaVersionImpl()` without logs

2023-04-28 15:40 UTC, alban-auzeill commented on java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/internal/InternalCheckVerifier.java
> +        "Preview features can only be enabled for the latest supported Java version (%d)",
`for the latest supported Java version (%d)` => `when the version >= latest supported Java version (>= %d)`

2023-05-01 09:03 UTC, alban-auzeill approved these changes

2023-05-01 09:04 UTC, merged