SONARJAVA-4526  Update Java parser version to ECJ 3.34.0
SonarSource/sonar-java pull request #4411
Opened 2023-06-23 14:03 UTC by alban-auzeill

2023-06-23 14:29 UTC, alban-auzeill commented on java-checks/src/main/java/org/sonar/java/checks/KnownCapacityHashBasedCollectionCheck.java
> +    return version.isJava20Compatible();
We should not change the above line. This rule tries to enforce new Java methods introduced in Java 19, not 20.
Like [HashMap#newHashMap(int)](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/util/HashMap.html#newHashMap(int))

2023-06-26 08:54 UTC, ADarko22 requested changes

2023-06-26 08:54 UTC, ADarko22 commented on sonar-java-plugin/pom.xml
> +              <minimizeJar>false</minimizeJar>
we should revert the flag to true and clean the filters: find the dependency with the Class that is not found and remove all the others that are not necessary but included transitively

2023-07-03 08:12 UTC, alban-auzeill commented
We are closing this PR without merging it because:
* ECJ 3.34 still has a bug and fails to parse some "when" identifiers. It was the main motivation to update.
* ECJ 3.34 now requires Java 17. It contradicts our scanner context requirements (Java 11) and during this sprint, we learned that there are no easy and reliable solutions to convert this dependency to target Java 11.

For more details see [SONARJAVA-4526](https://sonarsource.atlassian.net/browse/SONARJAVA-4526)

2023-07-03 08:13 UTC, alban-auzeill commented
We are closing this PR without merging it because:
* ECJ 3.34 still has a bug and fails to parse some "when" identifiers. It was the main motivation to update.
* ECJ 3.34 now requires Java 17. It contradicts our scanner context requirements (Java 11) and during this sprint, we learned that there are no easy and reliable solutions to convert this dependency to target Java 11.

For more details see [SONARJAVA-4526](https://sonarsource.atlassian.net/browse/SONARJAVA-4526)

2023-07-03 08:13 UTC, closed without merging