SONARJAVA-4676 S6829: @Autowired should be used when multiple constru…
SonarSource/sonar-java pull request #4508
Opened 2023-10-27 07:22 UTC by irina-batinic-sonarsource

2023-10-27 08:13 UTC, dorian-burihabwa-sonarsource requested changes
The implementation looks pretty solid to me. There are a couple of tweaks to do in the spec and test sample but there is also a question to answer about raising when some fields are marked as autowired

2023-10-27 08:13 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S6829.json
> +  "title": "@Autowired should be used when multiple constructors are provided",
Do we have a convention on "quoting" annotations in rule titles?

2023-10-27 08:13 UTC, dorian-burihabwa-sonarsource commented on java-checks-test-sources/src/main/java/checks/spring/AutowiredOnConstructorWhenMultipleConstructorsCheck.java
Should we nest all these example classes within another class? It might be nothing but I worry that every time we had a new top-level public class to `java-check-test-sources` we risk polluting the semantics of the whole module and encounter weird bugs when analyzing

2023-10-27 08:13 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/spring/AutowiredOnConstructorWhenMultipleConstructorsCheck.java
Should we raise in cases where a field is marked as autowired? Because we also have a rule that incites developers to replace their autowired fields with autowired constructors.

2023-10-27 09:43 UTC, irina-batinic-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/spring/AutowiredOnConstructorWhenMultipleConstructorsCheck.java
IMO, it is better to separate those.
Keep this one concise and only check constructors.
But, if you want, we can discuss this over the call.

2023-10-27 12:35 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/spring/AutowiredOnConstructorWhenMultipleConstructorsCheck.java
No, you are right. Let's keep the 2 rules independent of one another

2023-10-30 09:16 UTC, dorian-burihabwa-sonarsource approved these changes
Thanks for the changes, LGTM 👍🏿

2023-10-30 12:58 UTC, merged