SONARJAVA-4678: mplement S6831: @Qualifier should not be used on @Bean methods
SonarSource/sonar-java pull request #4518
Opened 2023-10-31 12:49 UTC by ADarko22

2023-10-31 15:46 UTC, dorian-burihabwa-sonarsource requested changes

2023-10-31 15:46 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/spring/AvoidQualifierOnBeanMethodsCheck.java
> +        .withMessage("Remove this redundant \"@Qualifier\" annotation")
Let's add a `.` to finish the issue message
```suggestion
        .withMessage("Remove this redundant \"@Qualifier\" annotation.")
```

2023-11-01 08:38 UTC, ADarko22 commented on java-checks/src/main/java/org/sonar/java/checks/spring/AvoidQualifierOnBeanMethodsCheck.java
> +        .addTextEdit(JavaTextEdit.removeTree(qualifierAnnotation))
quick fix tested locally and works; anyway comments on the same line are not remove (i.e. the // Noncompliant int he sample)

2023-11-01 10:26 UTC, dorian-burihabwa-sonarsource requested changes
Looking nice on the QF front, let's make sure we cover all our angles and fix the open issues

2023-11-01 10:26 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/spring/AvoidQualifierOnBeanMethodsCheck.java
> +    return qualifierAnnotationValue;
I understand checking the types twice just to be sure but in practice I am not sure if we are likely to see other types of arguments. Have you encountered any other while testing?

2023-11-01 10:26 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/spring/AvoidQualifierOnBeanMethodsCheck.java
> +      qualifierAnnotationValue = ((LiteralTreeImpl) ((AssignmentExpressionTreeImpl) argument).expression()).value().replace("\"", "");
Is it possible to set the value of the assignment expression using a constant?
```java
class A {
  static final String CONSTANT = "foo";
  @Bean  
  @Qualifier(value = CONSTANT)
  public String foo() { return "Hello"; }
}
```
I know that it is possible for the `@Variable` annotation. We should just make sure it is safe for our code to assume that we always have a literal

2023-11-02 14:34 UTC, dorian-burihabwa-sonarsource approved these changes
LGTM 👍🏿 Thanks for the changes

2023-11-02 14:56 UTC, merged