SONARJAVA-4832 Implement S6881
SonarSource/sonar-java pull request #4712
Opened 2024-03-12 15:04 UTC by johann-beleites-sonarsource

VirtualThreads should be used for tasks that include heavy blocking operations.

2024-03-18 15:31 UTC, johann-beleites-sonarsource commented
Please rebase, don't squash.

2024-03-19 14:55 UTC, irina-batinic-sonarsource reviewed
The implementation of the rule looks good, as does the fix for S1181. Good job!
I left a comment about the rule description on [this PR](https://github.com/SonarSource/rspec/pull/3780).

2024-03-20 17:56 UTC, irina-batinic-sonarsource commented on sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S6881.html
> +</pre>
I wondered why we have this Noncompliant code example without a corresponding Compliant Solution.

2024-03-21 10:05 UTC, leonardo-pilastri-sonarsource requested changes
Looks good! I think we can easily cover an extra way to construct a platform thread, then I think the PR is good to go!

2024-03-21 10:05 UTC, leonardo-pilastri-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/BlockingOperationsInVirtualThreadsCheck.java
> +      case METHOD -> onMethodFound((MethodTree) tree);
```suggestion
      case METHOD -> onMethodFound((MethodTree) tree);
      case METHOD_INVOCATION -> onMethodInvocationFound((MethodInvocationTree) tree);
```

2024-03-21 10:05 UTC, leonardo-pilastri-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/BlockingOperationsInVirtualThreadsCheck.java
> +
And with this fairly simple implementation we should be able to cover the extra constructor!
```

  private void onMethodInvocationFound(MethodInvocationTree tree) {
    var builderType = ((MemberSelectExpressionTree) tree.methodSelect()).expression().symbolType();
    if (threadCreationConstructors.matches(tree) && builderType.is("java.lang.Thread$Builder$OfPlatform")) {
      analyzeForIssues(tree.arguments().get(0), tree.methodSelect());
    }
  }
```

2024-03-21 14:55 UTC, leonardo-pilastri-sonarsource approved these changes
Nice work!

2024-03-21 15:20 UTC, merged