SONARJAVA-4835: Fix FNs when using generic types
SonarSource/sonar-java pull request #4716
Opened 2024-03-14 11:10 UTC by ADarko22

Please ensure your pull request adheres to the following guidelines: 

- [ ] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [ ] Unit tests are passing and you provided a unit test for your fix
- [ ] ITs should pass : To run ITs locally, checkout the [README](https://github.com/SonarSource/sonar-java/blob/master/README.md) of the project.
- [ ] If there is a [Jira](http://jira.sonarsource.com/browse/SONARJAVA) ticket available, please make your commits and pull request start with the ticket number (SONARJAVA-XXXX)

2024-03-14 14:31 UTC, kaufco approved these changes
LGTM! Maybe add a more complex test case with generics (which I expected to break the implementation, but it didn't)?

```
  public static class Phi {
    public List<? extends Number> getOtherThanOwnerType() {
      return null;
    }
  }

  public static class Theta extends Phi {
    @Override
    public List<Integer> getOtherThanOwnerType() {
      return null;
    }
  }

  public List<Integer> getNonRelatedA(Theta theta) { // Compliant
    return theta.getOtherThanOwnerType();
  }
  
  public List<? extends Number> getNonRelatedB(Theta theta) { // FN
    return theta.getOtherThanOwnerType();
  }
```

2024-03-14 14:39 UTC, ADarko22 commented
I'm adding those test cases. Note that 
```
  public List<? extends Number> getNonRelatedB(Theta theta) { // FN
    return theta.getOtherThanOwnerType();
  }
```
is not a FN. It is reported as TP :)

2024-03-14 17:09 UTC, kaufco requested changes
Sadly, it turned out that my example above indeed creates an FP, which was just masked by a bug that appears when the same method name is used.

As discussed: I'd suggest to close this PR and not to report on types with type parameters.

2024-03-15 11:42 UTC, ADarko22 commented on java-checks-test-sources/default/src/main/java/checks/LeastSpecificTypeCheck.java
> -
extracted and re-organized the test samples into a separate sample file

2024-03-15 15:05 UTC, kaufco approved these changes
LGTM! I didn't find a counterexample for the Generics. However, this seems like a lot of test cases. I'll approve anyway, but before merging, maybe you should think about if you can reduce them and which of them really increases the coverage.

2024-03-15 15:05 UTC, merged