SONARJAVA-5089 S1312 should not report on interfaces
SonarSource/sonar-java pull request #4858
Opened 2024-09-11 09:24 UTC by pauloreilly-sonarsource

Should not report on interfaces since fields cannot be private and static final is redundant.

2024-09-11 10:44 UTC, pauloreilly-sonarsource commented
Currently, Ruling Issues Number Differences check is failing due to LOGGER issue on Interfaces no longer being raised.

2024-09-13 08:19 UTC, kaufco approved these changes
Lgtm, but I'd suggest to change the comment before merging.

2024-09-13 08:24 UTC, kaufco requested changes
We should add a unit test for the new case (-> Logger declared inside an interface). Also, one suggestion about changing a comment. Otherwise, the PR looks good!

2024-09-13 15:39 UTC, kaufco approved these changes
Lgtm!

2024-09-13 15:40 UTC, merged