SONARJAVA-5158 update issue message
SonarSource/sonar-java pull request #4964
Opened 2024-12-16 16:31 UTC by erwan-serandour

[SONARJAVA-5158](https://sonarsource.atlassian.net/browse/SONARJAVA-5158)

Part of 

[SONARJAVA-5158]: https://sonarsource.atlassian.net/browse/SONARJAVA-5158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-12-18 16:47 UTC, dorian-burihabwa-sonarsource requested changes

2024-12-18 16:47 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/MismatchPackageDirectoryCheck.java
> +        String issueMessage = MessageFormat.format(MESSAGE, truncatedPath, packageName.replace(File.separator, "."));
Can we replace `MessageFormat` and use `String.format`? Or is there a specific reason to use the former?

2024-12-18 16:47 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/MismatchPackageDirectoryCheck.java
> +        String truncatedPath = dir.substring(srcIndex == -1 ? 0 : srcIndex);
I understand that by convention, java files should be placed under `src/{main|test}/java`, but users can customize the location where their sources are located. Can we use the module specific source directory to match?

2024-12-19 09:00 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/MismatchPackageDirectoryCheck.java
> +        String truncatedPath = dir.substring(srcIndex == -1 ? 0 : srcIndex);
After discussion, a simpler approach is to use `sonar.projectBaseDir` as the base root

2025-01-10 15:04 UTC, dorian-burihabwa-sonarsource requested changes

2025-01-10 15:04 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/MismatchPackageDirectoryCheck.java
> +        truncatedPath = String.join(File.separator, path);
We should extract part of the code could leave in its own method. Right now, it is using and re-assigning variables defined outside of the try block, which are also used outside of the try block

2025-01-10 15:56 UTC, erwan-serandour commented on java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/CheckVerifierTestUtils.java
> +  }
This is a mock java check with the purpose to test that property root project directory corresponds to what is expected. But indeed the message and the variable name is confusing.

2025-01-10 15:59 UTC, erwan-serandour commented on java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/CheckVerifierTestUtils.java
> +  }
:+1:

2025-01-10 16:07 UTC, erwan-serandour commented on java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/InternalCheckVerifierTest.java
> +      .isInstanceOf(UnsupportedOperationException.class);
:+1:

2025-01-10 16:07 UTC, erwan-serandour commented on java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/internal/JavaCheckVerifier.java
> +  }
:+1:

2025-01-10 16:19 UTC, erwan-serandour commented on java-checks/src/main/java/org/sonar/java/checks/MismatchPackageDirectoryCheck.java
> +        truncatedPath = String.join(File.separator, path);
:+1:

2025-01-27 13:06 UTC, dorian-burihabwa-sonarsource commented on java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/CheckVerifierTestUtils.java
> +        throw new RuntimeException("Expected rootProjectWorkingDirectory does not match context.getRootProjectWorkingDirectory");
Looking at the test in [InternalCheckVerifierTest](https://github.com/SonarSource/sonar-java/blob/3d14b7f92bcb1c33a7f278af371a2edc82ba655c/java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/InternalCheckVerifierTest.java), I don't understand how we ever go through this line

2025-01-27 13:07 UTC, dorian-burihabwa-sonarsource commented on java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/CheckVerifierTestUtils.java
> +        throw new RuntimeException("Expected rootProjectWorkingDirectory does not match context.getRootProjectWorkingDirectory");
Is this check necessary?

2025-01-27 13:07 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/MismatchPackageDirectoryCheck.java
> +    // In this case, path match package name.
```suggestion
    // In this case, path matches package name.
```

2025-01-27 13:10 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/MismatchPackageDirectoryCheck.java
> +      // NullPointerExceptions should not be thrown when accessing rootDirectory, but for now some context do it. See: SONARJAVA-5158.
I am not sure where in the ticket an explanation is provided for the contexts where an issue is raised. Can we be more explicit and self-contained here?

2025-01-27 13:11 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/MismatchPackageDirectoryCheck.java
> +  ) {
Let's try and simplify the reading by keeping things on the same line
```suggestion
  private static String truncateFileDirectoryPath(File fileDirectory, String rootProjectDirectoryName) {
```

2025-01-27 13:34 UTC, dorian-burihabwa-sonarsource commented on java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/CheckVerifierTestUtils.java
> +        throw new RuntimeException("Expected rootProjectWorkingDirectory does not match context.getRootProjectWorkingDirectory");
Let's move this check to `context_return_good_root_working_directory` as an anonymous class and replace the `if` statement with an assertion.

2025-01-27 13:34 UTC, dorian-burihabwa-sonarsource commented on java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/InternalCheckVerifierTest.java
> +        .withCheck(new CheckVerifierTestUtils.VerifyRootProjectWorkingDirectory(rootWorkDir))
The reference to `CheckVerifierTestUtils.VerifyRootProjectWorkingDirectory` can be removed since the code will fail on the next line before the check is invoked

2025-01-27 13:35 UTC, dorian-burihabwa-sonarsource commented on java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/InternalCheckVerifierTest.java
> +        .withRootDirectory(rootWorkDir);
```suggestion
 InternalCheckVerifier internalCheckVerifier = InternalCheckVerifier.newInstance()
      .onFile(TEST_FILE)
      .withCheck(new CheckVerifierTestUtils.VerifyRootProjectWorkingDirectory(rootWorkDir));

    Throwable e = catchThrowable(() -> {
      internalCheckVerifier
        .withRootDirectory(rootWorkDir);
```

2025-01-27 13:45 UTC, erwan-serandour commented on java-checks-test-sources/default/src/main/java/checks/mismatchPackage/DefaultPackage.java
> +class DefaultPackageCase{}
:+1:

2025-01-27 13:59 UTC, erwan-serandour commented on java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/InternalCheckVerifierTest.java
> +        .withCheck(new CheckVerifierTestUtils.VerifyRootProjectWorkingDirectory(rootWorkDir))
:+1:

2025-01-27 14:02 UTC, erwan-serandour commented on java-checks/src/main/java/org/sonar/java/checks/MismatchPackageDirectoryCheck.java
> +  ) {
:+1:

2025-01-28 16:24 UTC, merged