SONARJAVA-5262 Fix FP on S2187 in Cucumber tests with JUnit5.
SonarSource/sonar-java pull request #4972
Opened 2024-12-24 13:59 UTC by tomasz-tylenda-sonarsource

2025-01-07 10:27 UTC, tomasz-tylenda-sonarsource commented
This PR is not stale. It was on hold during holidays.

2025-01-10 09:37 UTC, dorian-burihabwa-sonarsource requested changes

2025-01-10 09:37 UTC, dorian-burihabwa-sonarsource commented on java-checks-test-sources/default/src/test/java/checks/tests/NoTestInTestClassCheckCucumberTest.java
> +@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value="com.project.class.path")
Is this part of the code needed to test the scenario in the ticket?

2025-01-10 09:37 UTC, dorian-burihabwa-sonarsource commented on java-checks/src/main/java/org/sonar/java/checks/tests/NoTestInTestClassCheck.java
> +          Objects.deepEquals(annotationValue.value(), new Object[]{"cucumber"}));
What happens here if we have a case where we have multiple values for the annotation? See this [example](https://github.com/yuzawa-san/googolplex-theater/blob/e3a3b2c7edb68646d6c6e5a4972577ab171ab427/src/test/java/com/jyuzawa/googolplex_theater/RunCucumber.java#L14)

2025-01-10 12:44 UTC, tomasz-tylenda-sonarsource commented on java-checks-test-sources/default/src/test/java/checks/tests/NoTestInTestClassCheckCucumberTest.java
> +@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value="com.project.class.path")
No and neither is `@Suite`. I originally included everything that was reported to us to make the test more realistic. Here I deleted the annotation that we don't need. This change let me remove cucumber from `pom.xml`.

2025-01-10 16:44 UTC, dorian-burihabwa-sonarsource requested changes
I think we can complete the coverage by testing a class test annotated with type clashes
```java
@IncompatibleAnnotations.IncludeEngines(42)
class ClassWithFakeIncludeEnginesAnnotationTest {// Noncompliant
}

class IncompatibleAnnotations {
  @interface IncludeEngines {
    int value();
  }
}
```

2025-01-20 14:35 UTC, dorian-burihabwa-sonarsource approved these changes

2025-01-20 14:41 UTC, merged